name: Check Links

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Links
      run: cargo run -- ../README.md
      working-directory: ci
